export const CANTO_TITLES: Record<number, string> = {
  1: "Los dioses deciden en asamblea el retorno de Odiseo",
  2: "Telémaco reúne en asamblea al pueblo de Ítaca",
  3: "Telémaco viaja a Pilos para informarse sobre su padre",
  4: "Telémaco viaja a Esparta para informase sobre su padre",
  5: "Odiseo llega a Esqueria de los feacios",
  6: "Odiseo y Nausícaa",
  7: "Odiseo en el palacio de Alcínoo",
  8: "Odiseo agasajado por los feacios",
  9: "Odiseo cuenta sus aventuras: los Cicones, los Lotófagos, los Cíclopes",
  10: "La isla de Eolo. El palacio de Circe la hechicera",
  11: "Descensus ad inferos (El Reino de los Muertos)",
  12: "Las sirenas, Escila y Caribdis. La Isla del Sol. Ogigia",
  13: "Los feacios despiden a Odiseo. Llegada a Ítaca",
  14: "Odiseo en la majada de Eumeo",
  15: "Telémaco regresa a Ítaca",
  16: "Telémaco reconoce a Odiseo",
  17: "Odiseo mendiga entre los pretendientes",
  18: "Los pretendientes vejan a Odiseo",
  19: "La esclava Euriclea reconoce a Odiseo",
  20: "La última cena de los pretendientes",
  21: "El certamen del arco",
  22: "La venganza",
  23: "Penélope reconoce a Odiseo",
  24: "El pacto"
};
